repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: end-of-file-fixer
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint
        name: markdownlint
        entry: markdownlint
        language: node
        files: \.md$
  - repo: https://github.com/errata-ai/vale
    rev: v3.7.1
    hooks:
      - id: vale
        name: vale
        entry: vale
        language: system
        files: \.md$
        args: [--config=.vale.ini]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        additional_dependencies: [prettier@2.3.2]
