name: Build and Deploy

on:
  push:
    paths:
      - "posts/*.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Hugo
        run: |
          sudo apt-get update
          sudo apt-get install -y hugo

      - name: Build the site
        run: make build
